name: Create PR for release/{app}

on:
  push:
    branches:
    - release/*

jobs:
  create-pull-requests:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: create pull request
      run: |
        git fetch origin main
        
        EARLIER_PR=$(gh pr list --head ${{ github.ref_name }} --state open --json url --jq .[].url)
        if [ -n "$EARLIER_PR" ]; then
          gh pr edit \
            -B main \
            -H ${{ github.ref_name }} \
            --fill-first
        fi
        gh pr create \
          -B main \
          -H ${{ github.ref_name }} \
          --fill-first || exit 0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
