name: Create PR for release/{app}

on:
  push:
    branches:
    - release/*

jobs:
  create-pull-requests:
    runs-on: ubuntu-latest
    permissions:
      pull-request: write
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: create pull request
      run: |
        gh pr create \
          -B main \
          -H ${{ github.ref_name }} \
          --title "test title" \
          --body "test body"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
